### ISSUE TITLE
Handle users who are currently over their record limit

### ISSUE THREAD

**Issue by bluefuton** [annacmc/records-meter#20]
If a user has paid for a 1000 record tier, and they currently have 1200 records, then:
* the chart should not melt/explode and still display the correct breakdown
* we should show the user a nudge that they'll be upgraded for their next billing cycle

**Comment by annacmc** [comment]
If a user is over their record limit, the chart does not melt/explode and it does now still display the correct breakdown. 
A nudge is added in the form of a notice which lets them know. It looks like this:

![image](https://user-images.githubusercontent.com/30754158/149198051-c40068ad-8290-48cf-9a85-516952cbb4da.png)

**Comment by bluefuton** [comment]
Yay for no melting or explosion.
