### ISSUE TITLE
Handle users who don't have any records at all

### ISSUE THREAD

**Issue by bluefuton** [annacmc/records-meter#25]
For users who don't have any records at all (but indexing is completed), we could either show an empty bar or a custom message.

In any case, let's make sure the chart still renders correctly when no data is provided.

**Comment by annacmc** [comment]
If a user has no records at all (but indexing is complete) it shows a custom message without a bar, which looks like this:
![image](https://user-images.githubusercontent.com/30754158/149197795-2750969f-8f87-42cb-bd20-79ac03c259c2.png)
